
FROM python:3.9-slim-buster
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY dags /app/dags
COPY etl /app/etl
EXPOSE 5000
CMD ["python", "dags/web_app.py"]
